src/Estore.Management.Web/Controllers/PurchaseOrderListController.cs
using Estore.Management.Library.PurchaseOrders;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Mobile.Estore.Web.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [Authorize]
    public class PurchaseOrderListController : Controller
    {
        /// <summary>
        /// 
        /// </summary>
        private readonly IPurchaseOrder purchaseOrder;

        /// <summary>
        /// 
        /// </summary>
        private readonly IPurchaseOrderList purchaseOrderList;

        /// <summary>
        /// 
        /// </summary>
        public PurchaseOrderListController()
        {
            this.purchaseOrder = new PurchaseOrder();
            this.purchaseOrderList = new PurchaseOrderList();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="catelogId"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<ActionResult> Index(decimal catelogId, string displayName)
        {
            ViewBag.CatelogName = displayName;
            ViewBag.CatelogId = catelogId;
            var model = await purchaseOrderList.Get(catelogId);
            return View(model);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="catelogId"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<ActionResult> New(PurchaseOrderDao dao)
        {
            ViewBag.CatelogId = dao.CatelogId;
            await purchaseOrder.New(dao);
            return RedirectToAction("Index", new { @catelogId = dao.CatelogId, @displayName = dao.CatelogDisplayName });
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="catelogId"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<ActionResult> Remove(decimal purchaseOrderId, decimal catelogId, string displayName)
        {
            ViewBag.CatelogId = catelogId;
            await purchaseOrder.Remove(purchaseOrderId);
            return RedirectToAction("Index", new { @catelogId = catelogId, @displayName = displayName });
        }
    }
}

src/Estore.Management.Web/Views/PurchaseOrderList/Index.cshtml
@model IEnumerable<Estore.Management.Library.PurchaseOrders.PurchaseOrderDao>
@{
    ViewBag.Title = "Catelog list";
    ViewBag.ActiveMenu = "Catelogs";
    ViewBag.Brands = Estore.Management.Library.Brands.BrandList.Get();
    Layout = "~/Views/Shared/IndexViewLayout.cshtml";
}
<div class="main-content">
    <div class="breadcrumbs" id="breadcrumbs">
        <ul class="breadcrumb">
            <li><i class="icon-home home-icon"></i><a href="#" style="color:maroon !important;">Home</a> </li>
            <li><i class="icon-briefcase"></i>&nbsp;<a href="#" style="color:maroon !important;">Catelogs</a></li>
            <li><i class="icon-mobile-phone"></i>&nbsp;<a href="#" style="color:maroon !important">Purchase Orders</a></li>
        </ul>
    </div>
    <div class="page-content">
        <div class="row" style="height:50px;">
            <div class="col-md-10">
                <h3>
                    <i class="icon-mobile-phone"></i>
                    PO for @ViewBag.CatelogName
                </h3>
            </div>
            <div class="col-md-2" style="text-align:right;vertical-align:bottom;padding-top:20px;">
                <span id="btnNewPurchaseOrder" class="btn btn-sm btn-success">
                    <i class="icon-plus-sign-alt" style="margin-right:6px;"></i>New
                </span>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="table-responsive">
                    <table class="table-bordered table-striped table-condensed" style="width:100%;">
                        <thead>
                            <tr>
                                <th>
                                    <i class="icon-calendar"></i>
                                    Date
                                </th>
                                <th>
                                    <i class="icon-rupee"></i>
                                    Price per piece
                                </th>
                                <th>
                                    <i class="icon-camera-retro"></i>
                                    Quantity
                                </th>
                                <th>
                                    <i class="icon-camera-retro"></i>
                                    GST %
                                </th>
                                <th>
                                    <i class="icon-camera-retro"></i>
                                    Sub total
                                </th>
                                <th>
                                    <i class="icon-camera-retro"></i>
                                    Tax amount
                                </th>
                                <th>
                                    <i class="icon-rupee"></i>
                                    Total amount
                                </th>
                                <th>

                                </th>
                            </tr>
                        </thead>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    <i class="icon-calendar"></i>
                                    @item.OrderDate.ToString("dd-MMMM-yyyy")
                                </td>
                                <td>
                                    <i class="icon-rupee"></i>
                                    @item.Price
                                </td>
                                <td>
                                    @item.Quantity
                                </td>
                                <td>
                                    @(item.TaxPercentage)
                                </td>
                                <td>
                                    <i class="icon-rupee"></i>
                                    @(item.Price * item.Quantity)
                                </td>
                                <td>
                                    <i class="icon-rupee"></i>
                                    @(item.TaxAmount)
                                </td>
                                <td>
                                    <i class="icon-rupee"></i>
                                    @((item.Price * item.Quantity) + Convert.ToDecimal(item.TaxAmount))
                                </td>
                                <td style="text-align:center;">
                                    <i class="icon-archive" style="cursor:pointer;" onclick="deletePurchaseOrder(@item.CatelogId, @item.PurchaseOrderId);"></i>
                                </td>
                            </tr>
                        }
                    </table>
                </div>
            </div>
        </div>
    </div>

    <!-- #region Modal -->
    <div class="modal fade" id="myModal" role="dialog">
        @{
            var dao = new Estore.Management.Library.PurchaseOrders.PurchaseOrderDao
            {
                PurchaseOrderId = 0,
                Quantity = 0,
                CatelogId = ViewBag.CatelogId,
                CatelogDisplayName = ViewBag.CatelogName
            };
        }
        @using (@Html.BeginForm("New", null, dao, FormMethod.Post))
        {
            @Html.HiddenFor(x => dao.PurchaseOrderId)
            @Html.HiddenFor(x => dao.CatelogId)
            @Html.HiddenFor(x => dao.CatelogDisplayName)
            <div class="modal-dialog">
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Please fill all required fields.!</h4>
                    </div>
                    <div class="modal-body">
                        <div class="row">
                            <div class="col-lg-12">
                                <span class="text-info">Order date</span>
                                <br />
                                <input type='date' name="dao.OrderDate" value="@DateTime.Now.ToString("yyyy-MM-dd")" class='form-control' />
                                <br />
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <span class="text-info">Price</span>
                                <br />
                                <input type='text' name="dao.Price" class='form-control' />
                                <br />
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <span class="text-info">Quantity</span>
                                <br />
                                <input type='text' name="dao.Quantity" class='form-control' />
                                <br />
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <span class="text-info">GST Applied</span>
                                <br />
                                <input type='text' name="dao.TaxPercentage" class='form-control' />
                                <br />
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <div class="col-lg-12">
                            <button class="btn btn-success" type="submit">Save</button>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
    <!-- #endRegion Modal -->
    <!-- #region Script -->
    <script type="text/javascript">
        $(document).ready(function () {
            $('#btnNewPurchaseOrder').click(function () {
                $('#myModal').modal();
            });
        });

        function deletePurchaseOrder(catelogId, purchaseOrderId) {
            if (confirm('Are you sure to delete?')) {
                var displayName = '@ViewBag.CatelogName';
                var url = '@Html.Raw(Url.Action("Remove", "PurchaseOrderList", new { catelogId = "__catelogId__", purchaseOrderId = "__purchaseOrderId__", displayName = "__displayName__"}))';
                window.location.href = url.replace("__catelogId__", catelogId).replace("__purchaseOrderId__", purchaseOrderId).replace("__purchaseOrderId__", purchaseOrderId).replace("__displayName__", displayName).replace("#", "%23");
            }
        }

    </script>
    <!-- #endRegion Script -->
</div>