src/Estore.Management.Web/Controllers/CatelogListController.cs
using Estore.Management.Library.Catelogs;
using System;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Mobile.Estore.Web.Controllers
{
    [Authorize]
    public class CatelogListController : Controller
    {
        /// <summary>
        /// 
        /// </summary>
        private readonly ICatelogList catelogList;

        /// <summary>
        /// 
        /// </summary>
        private readonly ICatelog catelog;

        /// <summary>
        /// 
        /// </summary>
        /// <param name="billOrder"></param>
        /// <param name="billOrderDal"></param>
        public CatelogListController()
        {
            catelogList = new CatelogList();
            catelog = new Catelog();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public async Task<ActionResult> Index(int? brandTypeId = null)
        {
            ViewBag.BrandTypeId = brandTypeId != null ? brandTypeId : -1;
            var model = await catelogList.Get(brandTypeId);
            return View(model);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="dao"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<ActionResult> Save(CatelogDao dao)
        {
            if(dao.CatelogId == 0)
            {
                await catelog.New(dao);
            }
            else
            {
                await catelog.Save(dao);
            }
            return RedirectToAction("Index", new { @brandTypeId = dao.BrandTypeId });
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="brandTypeId"></param>
        /// <param name="catelogId"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<ActionResult> Update(decimal catelogId, int? brandTypeId = null)
        {
            await catelog.Status(catelogId);
            return RedirectToAction("Index", new { brandTypeId });
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public async Task<JsonResult> Get(decimal catelogId)
        {
            var model = await catelog.Get(catelogId);
            return Json(model, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="selectedDate"></param>
        /// <param name="catelogId"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<JsonResult> Search(DateTime selectedDate, decimal catelogId = 0)
        {
            var model = await catelogList.Get(selectedDate, catelogId);
            return Json(model, JsonRequestBehavior.AllowGet);
        }
    }
}

src/Estore.Management.Web/Controllers/DailyCatelogReportController.cs
using Estore.Management.Library.Reports;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Mobile.Estore.Web.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [Authorize]
    public class DailyCatelogReportController : Controller
    {

        /// <summary>
        /// 
        /// </summary>
        private readonly IReport<List<DailyCatelogSaleDao>, DailyCatelogSaleCriteria> report;

        /// <summary>
        /// 
        /// </summary>
        public DailyCatelogReportController()
        {
            this.report = new DailyCatelogSale();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="date"></param>
        /// <returns></returns>
        public async Task<ActionResult> Index(string date)
        {
            DateTime dateTime;
            if (string.IsNullOrEmpty(date))
            {
                dateTime = DateTime.Now.Date;
            }
            else
            {
                dateTime = DateTime.ParseExact(date, "yyyy-MM-dd", null);
            }
            ViewBag.SelectedDate = dateTime;
            var list = await report.Get(new DailyCatelogSaleCriteria(dateTime));
            return View(list);
        }
    }
}

src/Estore.Management.Web/Views/DailyCatelogReport/Index.cshtml
@model IEnumerable<Estore.Management.Library.Reports.DailyCatelogSaleDao>
@{
    ViewBag.Title = "Catelog Report";
    ViewBag.ActiveMenu = "DailyCatelogSaleReport";
    Layout = "~/Views/Shared/IndexViewLayout.cshtml";
}
<div class="main-content">
    <div class="breadcrumbs" id="breadcrumbs">
        <ul class="breadcrumb">
            <li><i class="icon-home home-icon"></i><a href="#" style="color:maroon !important;">Home</a> </li>
            <li><i class="icon-file-text-alt"></i>&nbsp;<a href="#" style="color:maroon !important;">Catelog Report</a></li>
        </ul>
    </div>
    <div class="page-content">
        <div class="row" style="height:60px;">
            <div class="col-md-8">
                <h3><i class="icon-file-text-alt"></i>&nbsp;Catelog sale report for @ViewBag.SelectedDate.ToString("dd-MMMM-yyyy")</h3>
            </div>
            <div class="col-md-4" style="text-align:right;vertical-align:middle;padding-top:20px;padding-bottom:10px;">
                <input type="date" value="@ViewBag.SelectedDate.ToString("yyyy-MM-dd")" onchange="loadDailySale(this.value);" />
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <table class="table-hover table-bordered table-striped table-condensed" style="width:100%;">
                    <thead>
                        <tr>
                            <th style="width:70%;padding-left:5px;color:#333;font-weight:normal;">
                                <i class="icon-male"></i>
                                Name
                            </th>
                            <th style="width:20%;padding-left:5px;color:#333;font-weight:normal;">
                                <i class="icon-camera-retro"></i>
                                Quantity
                            </th>
                            <th style="width:10%;padding-left:5px;color:#333;font-weight:normal;">

                            </th>
                        </tr>
                    </thead>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td style="padding-left:10px;">
                                @item.BrandName
                                @item.CatelogName
                            </td>
                            <td style="vertical-align:middle;text-align:left;font-size:13px;padding-left:10px;">
                                @item.Quantity
                            </td>
                            <td>
                                <i class="icon-th-list" style="cursor:pointer;" onclick="loadRetailerListForSpecificCatelog('@item.CatelogId', '@item.BrandName' +  '@item.CatelogName');"></i>
                            </td>
                        </tr>
                    }
                    <tr>
                        <td></td>
                        <td style="padding-left:10px;" colspan="2">
                            <b>
                                @Model.Sum(x => x.Quantity)
                            </b>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>

    <!-- #region Modal -->
    <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title"><span id="catelogNameRetailerList"></span> - Retailer's list</h4>
                </div>
                <div class="modal-body">
                    <span id="tblRetailerList"></span>
                </div>
            </div>
        </div>
    </div>
    <!-- #endRegion Modal -->
    <!-- #region Script -->
    <script type="text/javascript">
        function loadDailySale(selectedDate) {
            var url = '@Html.Raw(Url.Action("Index", "DailyCatelogReport", new { date = "__date__"}))';
            window.location.href = url.replace("__date__", selectedDate).replace("#", "%23");
        }

        function loadRetailerListForSpecificCatelog(catelogId, catelogName) {
            var selectedDate = '@ViewBag.SelectedDate.ToString("yyyy-MM-dd")';
            var apiUrl = '@Html.Raw(Url.Action("Search", "CatelogList", new { catelogId = "__catelogId__", selectedDate = "__selectedDate__" }))';
            $.ajax(apiUrl.replace("__catelogId__", catelogId).replace("__selectedDate__", selectedDate),
            {
                success: function (data) {
                    document.getElementById('tblRetailerList').innerHTML = "";
                        var htmlLines = "";
                    var htmlTableRow = "<table class='table table-bordered table-striped table-condensed'><tr><td>&nbsp;Name</td><td>&nbsp;InvoiceNumber</td><td>&nbsp;Quantity</td></tr>";
                        for (var i = 0; i < data.length; i++) {
                            htmlLines += "<tr><td>&nbsp;" + data[i]["Name"] + "</td><td>&nbsp;" + data[i]["InvoiceNumber"] + "</td><td>&nbsp;" + data[i]["Quantity"] + "</tr>";
                        }
                        htmlLines += "</table>"
                    document.getElementById('tblRetailerList').innerHTML = htmlTableRow + htmlLines;
                    document.getElementById('catelogNameRetailerList').innerHTML = catelogName;
                    $('#myModal').modal();
                }
            });
        }
    </script>
    <!-- #endRegion Script -->

</div>