src/Estore.Management.Web/Controllers/CustomerBillListController.cs
using Estore.Management.Library.CustomerBills;
using System;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Mobile.Estore.Web.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [Authorize]
    public class CustomerBillListController : Controller
    {
        /// <summary>
        /// 
        /// </summary>
        private readonly ICustomerBill customerBill;

        /// <summary>
        /// 
        /// </summary>
        /// <param name="billOrder"></param>
        /// <param name="billOrderDal"></param>
        public CustomerBillListController()
        {
            customerBill = new CustomerBill();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public async Task<ActionResult> Index(string invoiceDate)
        {
            ViewBag.InvoiceDate = invoiceDate;
            var list = await customerBill.FetchList(invoiceDate);
            return View(list);
        }
    }
}

src/Estore.Management.Web/Views/CustomerBillList/Index.cshtml
@model IEnumerable<Estore.Management.Library.CustomerBills.CustomerBillDao>
@{
    ViewBag.Title = "Customer Bills";
    ViewBag.ActiveMenu = "Orders";
    Layout = "~/Views/Shared/IndexViewLayout.cshtml";
}
<script type="text/javascript">
    $(document).ready(function () {
        $(".datepicker").change(function () {
            var url = '@Url.Action("Index", "CustomerBillList", new { @invoiceDate = "__invoiceDate__" })';
            window.location.href = url.replace("__invoiceDate__", $(this).val());
        });
    });
</script>
<div class="main-content">
    <div class="breadcrumbs" id="breadcrumbs">
        <ul class="breadcrumb">
            <li><i class="icon-home home-icon"></i><a href="#" style="color:maroon !important;">Home</a> </li>
            <li><i class="icon-building"></i>&nbsp;<a href="#" style="color:maroon !important;">Customer Bills</a></li>
        </ul>
    </div>
    <div class="page-content">
        <div class="row" style="height:50px;">
            <div class="col-md-8">
                <h3 style="margin-top:12px;"><i class="icon-building"></i>&nbsp;Customer Bills</h3>
            </div>
            <div class="col-md-4" style="text-align:right;padding-top:5px;">
                <span class="btn btn-sm btn-success" style="padding-top:7px;padding-bottom:7px;">
                    <a style="color:white !important" href="~/CustomerBillEdit?invoiceDate=@ViewBag.InvoiceDate">
                        <i class="icon-plus-sign-alt"></i>&nbsp;New
                    </a>
                </span>
                &nbsp;&nbsp;
                <input type="date" class="datepicker" value='@ViewBag.InvoiceDate' />
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <table class="table-bordered table-striped table-condensed" style="width:100%;">
                    <thead>
                        <tr>
                            <th style="padding-left:5px;color:#333 !important;font-weight:normal;">
                                <i class="icon-camera-retro"></i>
                                Name
                                &
                                Address
                            </th>
                            <th style="padding-left:5px;color:#333 !important;font-weight:normal;">
                                <i class="icon-camera-retro"></i>
                                Model
                            </th>
                            <th style="padding-left:5px;color:#333 !important;font-weight:normal;">
                                <i class="icon-camera-retro"></i>
                                IMEI
                            </th>
                            <th style="padding-left:5px;color:#333 !important;font-weight:normal;">
                                <i class="icon-mobile-phone"></i>
                                Mobile number
                            </th>
                            <th style="padding-left:5px;color:#333 !important;font-weight:normal;">
                                <i class="icon-camera-retro"></i>
                                Battery number
                            </th>
                            <th style="padding-left:5px;color:#333 !important;font-weight:normal;">
                                <i class="icon-camera-retro"></i>
                                Charger number
                            </th>
                            <th style="padding-left:5px;color:#333 !important;font-weight:normal;">
                                <i class="icon-rupee"></i>
                                Grand total
                            </th>
                        </tr>
                    </thead>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td style="padding-left:8px;">
                                @item.Name
                                <br />
                                @item.Address
                            </td>
                            <td style="padding-left:8px;">
                                @if (item.CatelogId != null && item.CatelogId > 0)
                                {
                                    @item.CatelogDisplayName
                                }
                                else
                                {
                                    @item.ModelNumber
                                }
                            </td>
                            <td style="padding-left:8px;">
                                @item.IMEINumber1
                                @if (!string.IsNullOrEmpty(item.IMEINumber2))
                                {
                                    <br />
                                    <span style="line-height:23px;">
                                        @item.IMEINumber2
                                    </span>
                                }
                            </td>
                            <td style="padding-left:8px;">
                                <i class="icon-phone-sign"></i>
                                @item.MobileNumber
                            </td>
                            <td style="padding-left:8px;">
                                @item.BatteryNumber
                            </td>
                            <td style="padding-left:8px;">
                                @item.ChargerNumber
                            </td>
                            <td style="padding-left:8px;">
                                <i class="icon-rupee"></i>
                                @item.GrandTotal
                            </td>
                            <td style="padding-left:8px;text-align:left;">
                                <a style="background-color:transparent !important;color:black !important;font-size:15px !important;" href="~/PrintBill?invoiceId=@item.Id" target="_blank"
                                   onclick="return !window.open(this.href, 'Print Invoice', 'width=900,height=700')">
                                    <i class="icon-print"></i>
                                </a>
                            </td>
                            <td style="padding-left:8px;text-align:left;">
                                <a style="background-color:transparent !important;padding:2px !important;font-size:15px !important;color:black !important;" onclick="return confirm('Are you sure to delete this bill.?');" href="~/CustomerBillEdit/Delete?invoiceId=@item.Id&invoiceDate=@ViewBag.InvoiceDate">
                                    <i class="icon-archive"></i>
                                </a>
                            </td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>
</div>